// Mocks generated by Mockito 5.0.17 from annotations
// in awesome_app/test/features/example/data/repositories/example_r_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:awesome_app/core/network/base_response.dart' as _i2;
import 'package:awesome_app/features/example/data/datasources/example_data_source.dart'
    as _i3;
import 'package:awesome_app/features/example/domain/entities/example.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeApiResponse_0<T> extends _i1.Fake implements _i2.ApiResponse<T> {}

/// A class which mocks [ExampleRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleRemoteDataSource extends _i1.Mock
    implements _i3.ExampleRemoteDataSource {
  MockExampleRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Example>>> getExample() =>
      (super.noSuchMethod(Invocation.method(#getExample, []),
              returnValue: Future<_i2.ApiResponse<List<_i5.Example>>>.value(
                  _FakeApiResponse_0<List<_i5.Example>>()))
          as _i4.Future<_i2.ApiResponse<List<_i5.Example>>>);
}
