# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Grandle modules
        uses: actions/cache@v2.1.7
        env:
          cache-number: ${{ secrets.CACHE_NUMBER }}
        with:
          path: |
            ~/android/.gradle
            ~/.gradle/cache
            # ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.cache-number }}-${{ hashFiles('android/build.gradle') }}-${{ hashFiles('android/app/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('android/build.gradle') }}
            ${{ runner.os }}-gradle-${{ env.cache-name }}-
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Cache Flutter modules
        uses: actions/cache@v2.1.7
        env:
          cache-number: ${{ secrets.CACHE_NUMBER }}
        with:
          path: |
            ~/.pub-cache/bin
          key: ${{ runner.os }}-pub-${{ env.cache-number }}-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ env.flutter_version }}-
            ${{ runner.os }}-pub-
            ${{ runner.os }}-

      - name: Upgrade PATH
        run: export PATH="$PATH":"$HOME/.pub-cache/bin"

      - name: Get flutter dependencies.
        run: |
          flutter --version
          make dependencies
          make easy-location

      - name: Run build runner
        run: make build-runner

      - name: Check for any formatting and statically analyze the code.
        run: make format-analyze

      - name: Run Unit Test
        run: make unit-test

      - name: Build test apk
        run: make build-android-dev

      - name: Create Github Release
        run: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*-release.apk"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}